name: validate

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.tool-versions'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.tool-versions'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn prettier
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.tool-versions'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.tool-versions'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: 🧼 lint renovate config # Validates changes to renovate.json config file
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.1
        with:
          config_file_path: 'renovate.json'
